language: php

php: 7.2

sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor

before_install:
  - phpenv config-rm xdebug.ini || true
  - nvm install 8.1.2
  - npm install -g yarn@0.24.5

before_script:
  - composer install --prefer-source --no-interaction --dev
  - yarn install
  - yarn production

script:
  - vendor/bin/phpspec run --verbose
  - vendor/bin/phpunit --verbose

deploy:
  provider: script
  script: curl ${ENVOYER_DEPLOYMENT_HOOK}?sha=${TRAVIS_COMMIT}
  on:
    branch: master
