name: Prettier

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: npm ci

      - name: Run prettier
        run: npm run prettier --write 'src/**/*.{css,js,vue}'

      - uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Apply prettier changes
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
